### ISSUE TITLE
能否选择wiki的一级目录并进行下载该文件与子文件？

### ISSUE THREAD

**Issue by areuok2022** [dicarne/feishu-backup#11]
RT.

**Comment by hihihowareyou** [comment]
的确，这么搞比较稳定。Dicarne大佬有空整么。

**Comment by dicarne** [comment]
https://github.com/dicarne/feishu-backup/commit/9c583a16c92b14113ebfb4fa0b5ebdc47d1d634d
简单的支持了一下~
