### ISSUE TITLE
dicarne.github.io/feishu-backup  没有内容

### ISSUE THREAD

**Issue by lmmsoft** [dicarne/feishu-backup#12]
rt

**Comment by dicarne** [comment]
这个URL确实没有内容，但我不清楚你访问这个URL的目的是什么……
请通过 https://dicarne.github.io/feishu-backup/#/config 计算URL后再进行访问

**Comment by lmmsoft** [comment]
我的意思是这是主页，可以加个链接去config，哈哈

**Comment by dicarne** [comment]
也可以哈
