### ISSUE TITLE
有办法一键or一个api备份所有知识库的所有文档么？

### ISSUE THREAD

**Issue by lmmsoft** [dicarne/feishu-backup#15]
想用在github action里，做定时备份的任务

**Comment by dicarne** [comment]
可能有些困难，之前我也想这么搞，后来研究了半天，发现飞书的认证一定要到他那个网页去点，不然获得不了权限。
理论上可能可以获取一次认证，然后无限次续期。

**Comment by lmmsoft** [comment]
今天用大佬的工具备份了成功备份了公司全部的文档，非常感谢！

提个问题：单页面里，下载知识库时，只能等待无法并发。想要并发必须开多窗口，多次授权。

建议：(1) 一键下载全部知识库的按钮？ or (2)单页面里，可以并行下载每个知识库？

**Comment by dicarne** [comment]
> 

不知道为什么今天才看到。
不做并发的最大原因是之前并发下载老是超过飞书的API调用频率限制，然后总是会出错需要重试，搞了半天没达到加速的目的。

**Comment by dicarne** [comment]
一键下载可以考虑做！或者类似多选知识库下载
