### ISSUE TITLE
貌似现在新版的飞书个人版无法自己审核自己的应用发布。。尴尬了

### ISSUE THREAD

**Issue by jackdiy** [dicarne/feishu-backup#16]
是否有办法飞书个人版进行备份。。。似乎自己创建一个企业也无法将个人版的文档同步过去，只能手动把文档一个一个的创建副本到企业，也太慢了。。

**Comment by dicarne** [comment]
不能发布吗？我创建了个个人版，好像是可以发布的？
![image](https://user-images.githubusercontent.com/10357789/220556131-389c30c8-cf17-466e-abc1-2e6164b9e2f9.png)

**Comment by jackdiy** [comment]
> 

！？我是可以发布，但审核的时候我没办法审核。说要企业账号才能审核，难道有什么隐藏操作？

**Comment by dicarne** [comment]
好像确实不能更新……感觉是个逻辑上的bug，你问问客服？

**Comment by jackdiy** [comment]
> 好像确实不能更新……感觉是个逻辑上的bug，你问问客服？

客服没怎么回，看网站的错误是说，个人版用户没有企业应用的管理后台登录权限，所以不能自己审核自己的应用，这两天和客服再斗争一下试试，其实这个设定挺傻的。。个人版用户能创建应该就能审核，既然创建了又要求建个企业版账号

**Comment by dicarne** [comment]
对的，我怀疑是最近管理后台更新了，和开发者平台的流程对不上了

**Comment by jackdiy** [comment]
> 对的，我怀疑是最近管理后台更新了，和开发者平台的流程对不上了

今天客服团队来了个电话，说可否提供您之前可以发布审核通过个人版的AppID，参考用于内部团队沟通查询问题所在。如果您方便可以发一下，不方便，我觉得也不指望他们了。
官方目前的回复是
1、个人号云文档无论数量多少，暂时未提供批量迁移到企业账号的功能
2、个人账号发布云文档的应用，确实目前没有后台，不确定以前是不是可以审核。

**Comment by dicarne** [comment]
> > 对的，我怀疑是最近管理后台更新了，和开发者平台的流程对不上了
> 
> 今天客服团队来了个电话，说可否提供您之前可以发布审核通过个人版的AppID，参考用于内部团队沟通查询问题所在。如果您方便可以发一下，不方便，我觉得也不指望他们了。 官方目前的回复是 1、个人号云文档无论数量多少，暂时未提供批量迁移到企业账号的功能 2、个人账号发布云文档的应用，确实目前没有后台，不确定以前是不是可以审核。

我那个也不是审核通过，而是第一次新建的应用第一次发布不需要管理员审核自动通过了，后来更新，也不能审核发布了。
他们就不能自己试一试吗，以前我也没用过个人版

**Comment by jackdiy** [comment]
> 

感谢，没事，可能个人版他们不重视，哈哈

**Comment by dicarne** [comment]
> > 
> 
> 感谢，没事，可能个人版他们不重视，哈哈

看了最近的收费更新，我已经想溜了哈哈
