### ISSUE TITLE
本地部署baseUrl的设置问题

### ISSUE THREAD

**Issue by jeffersonchou** [dicarne/feishu-backup#18]
刚好有这个需求，感谢分享；config.ts中设置baseUrl：
```
    baseUrl: "https://open.feishu.cn/open-apis",
    baseUrl_noauth: "https://open.feishu.cn/open-apis"
```
遇到Cors问题，但如果设置为127.0.0.1:3800又无法调用接口，应该怎么处理？

**Comment by jeffersonchou** [comment]
另外，本地部署，这个地方也要改一下：
`const calculate = () => {
    if (appid.value === "" || appsecret.value === "") {
        redirect_url.value = "请填写ID和Secret"
    } else {
        redirect_url.value = `http://127.0.0.1:3800/#/backup/${appid.value}/${appsecret.value}`
        backup_url.value = `https://open.feishu.cn/open-apis/authen/v1/index?redirect_uri=${encodeURIComponent(redirect_url.value)}&app_id=${appid.value}`
    }
}`

**Comment by dicarne** [comment]
可以考虑用vite.config.ts中的server的proxy功能。
文档参考：https://cn.vitejs.dev/config/server-options.html#server-proxy

**Comment by dicarne** [comment]
或者本地开个nginx之类的进行反向代理

**Comment by jeffersonchou** [comment]
嗯，我试一下，感谢
