### ISSUE TITLE
云文档 下载哪儿，不能显示出 有哪些文档

### ISSUE THREAD

**Issue by wm7799** [dicarne/feishu-backup#2]
按照 github.com的说明，配置好了相关权限以及重定向URL后，发布应用。那边使用那个链接进去后，下载文档哪儿 报错，里面什么也没有

**Comment by wm7799** [comment]
![Uploading Screenshot_20220618_153400_com.huawei.browser_edit_25778438753356.jpg…]()

**Comment by dicarne** [comment]
等一下，现在有bug，我已经找到问题可能在哪了，在打包

**Comment by wm7799** [comment]
好的，感谢

**Comment by dicarne** [comment]
现在我这测试正常，你打开那个网页，然后Ctrl+R强制刷新一下试试

**Comment by wm7799** [comment]
能显示了，谢谢。

**Comment by wm7799** [comment]
本地部署那个  有更详细的步骤吗，有点看不懂。

**Comment by dicarne** [comment]
我改改吧

**Comment by wm7799** [comment]
感谢，感谢！！！

**Comment by dicarne** [comment]
完善了一下，需要一点nginx的知识

**Comment by wm7799** [comment]
这个能看懂，感谢
