### ISSUE TITLE
点击'下载知识库文档' 后没反应, 报错如图

### ISSUE THREAD

**Issue by sclongyang** [dicarne/feishu-backup#21]
![image](https://user-images.githubusercontent.com/13296537/225969947-c7e91670-7f95-4501-9432-d02b5e9d9de7.png)

点击"下载云空间文档"可以正常下载成功

**Comment by dicarne** [comment]
他们两个用的是同一个api，应该没道理一个能用另一个不能用啊……疑惑

**Comment by Kyire6** [comment]
> ![image](https://user-images.githubusercontent.com/13296537/225969947-c7e91670-7f95-4501-9432-d02b5e9d9de7.png)
> 
> 点击"下载云空间文档"可以正常下载成功

检查自建应用的权限是否全部开通，可以在应用管理的日志查询中看到详细报错信息的
