### ISSUE TITLE
关于一直显示”下载中“的无法正常使用的问题

### ISSUE THREAD

**Issue by Raymond-Hear** [dicarne/feishu-backup#23]
你好Dicarne。
我想问一下，我根据步骤进行配置，点击下载文件后一直处于这样的界面，无法下载成功 ，请问这是什么原因呢？（更换了几个文档都是这样的情况，刷新重试依旧是这样的情况）
![image](https://user-images.githubusercontent.com/55983690/230590674-9d349c39-5a3f-454d-b38c-5ce6c8d4b463.png)

**Comment by dicarne** [comment]
我刚才测试了一下，没有问题。
估计是你没有申请足够的权限。
或许可以F12打开开发者控制台看一下网络请求返回了什么。

**Comment by Raymond-Hear** [comment]
> 我刚才测试了一下，没有问题。 估计是你没有申请足够的权限。 或许可以F12打开开发者控制台看一下网络请求返回了什么。

是这里看吗？![image](https://user-images.githubusercontent.com/55983690/230595672-f6d4ef45-d8f8-41e9-96b1-3c5bc3709377.png)

**Comment by dicarne** [comment]
你重新点链接，重新认证试试……看不出来是什么原因

**Comment by dicarne** [comment]
认证出错也可能出现这些报错

**Comment by Raymond-Hear** [comment]
> 认证出错也可能出现这些报错

哦哦，刚重新授权了全部云文档权限，就下载成功了，果然是权限问题
