### ISSUE TITLE
json 文件是如何使用的

### ISSUE THREAD

**Issue by slowpy** [dicarne/feishu-backup#24]
json 文件是如何使用的？
下载后离线文件 用什么软件管理和编辑呢？求推荐
谢谢

**Comment by dicarne** [comment]
json是请求飞书服务器拿到的原始文件，携带原始信息，如果会编程的话可以用json重新导出你想要的格式……毕竟markdown并不能支持所有格式，比如排版等功能就不行。如果有人乐意的话，可以把json处理成有复杂排版的文档。
一般我用vscode编辑，不过json不是直接看的。markdown的话，我也用vscode就是了。

**Comment by slowpy** [comment]
> json是请求飞书服务器拿到的原始文件，携带原始信息，如果会编程的话可以用json重新导出你想要的格式……毕竟markdown并不能支持所有格式，比如排版等功能就不行。如果有人乐意的话，可以把json处理成有复杂排版的文档。 一般我用vscode编辑，不过json不是直接看的。markdown的话，我也用vscode就是了。

好的，谢谢了
