### ISSUE TITLE
secret.ts和配置nginx转发 有依赖关系吗？

### ISSUE THREAD

**Issue by GavinZJZhang** [dicarne/feishu-backup#25]
我的secret.ts写成：
import { Secret } from './secret_interface'
  2 export default {
  3     baseUrl: "http://13.52.252.266/open-apis",
  4     baseUrl_noauth: "http://13.52.252.266/open-apis"
  5 } as Secret
  
  那么我的nginx转发应该怎么配置呢？
  
  如下所示，则会报错502 bad gateway，应该如何解决？谢谢
  location /open-apis {
                  proxy_pass https://open.feishu.cn/open-apis;
                  add_header Access-Control-Allow-Origin *;
                  add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS';
                  add_header Access-Control-Allow-Headers 'DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,I    f-Modified-Since,Cache-Control,Content-Type,Authorization';
                  if ($request_method = 'OPTIONS') {
                          return 204;
                  }
         }

**Comment by dicarne** [comment]
这里看来你写的配置没什么问题，就是这么配的，所以可能是其他部分nginx的配置有问题
