### ISSUE TITLE
遇到了一个比较麻烦的问题,知识库过大下载不了

### ISSUE THREAD

**Issue by jackdiy** [dicarne/feishu-backup#26]
我目前的知识库有50多个文档,但加起来有13G左右,用网页下载似乎每次都无法断点续传,这就很头疼了.
是否有什么办法把知识库的文档列成一个一个的文档,虽然一个文档超过1个多G下载也有断点问题,但起码有重试成功的可能....
有什么好的思路吗?

**Comment by dicarne** [comment]
你这文档里啥东西这么大啊，图片？文件？
虽然可以考虑把知识库选择做成树形，就像文件那样。但最近没空改。

作为替代方案，你可以考虑在飞书知识库那个页面，点击想要的文件边上那三个点，打开菜单，点击创建副本，然后保存到我的空间。然后通过下载我的空间文档的方式下载。那个是支持选择单个文件的。

**Comment by jackdiy** [comment]
就是图片，你可以理解为我拿这玩意写了个巨大的图文文档，近百万字，每几百字有一张图。
没事，不急，我想办法如何变成单文件吧。
