### ISSUE TITLE
点击“下载云文档”后卡在“下载中”界面

### ISSUE THREAD

**Issue by zycmayo** [dicarne/feishu-backup#28]
点击“下载云文档”后，会显示一个“下载中”的界面，但是一直卡在这个界面，不能读取我的所有云文档，情况如图：
![1688376747632(1)](https://github.com/dicarne/feishu-backup/assets/138457036/b01ca1d2-d552-4c82-8641-a5c4238697ee)
偶然间进去一次，下载3个文档，也是卡在“下载中”，没有成功下载

**Comment by dicarne** [comment]
很怪，难道是我的服务器被飞书拉黑了？

**Comment by zycmayo** [comment]
> 
非常感谢您的回复！感觉这个比较考验运气。有的时候授权登录就需要很久的时间，有的时候点击”下载云文档“后会卡在“下载中”，如果能成功到最后一步，选择要下载的文档，在下载文件夹的时候也会一直在“下载中”的界面，不弹出让我选择保存下载位置的窗口。初步试了一下，330M的文件夹在“下载中”界面读取了20分钟没能弹出保存位置窗口，有一点奇怪

**Comment by dicarne** [comment]
我这里也是这样，很奇怪

**Comment by jackdiy** [comment]
我这也遇到此问题了，突然发生的，我还以为是上次那个问题，它超时后还会说没有权限。但API和Key应该没问题。怀疑是接口有一些变动。

**Comment by dicarne** [comment]
我看了下nginx的日志，nginx访问的飞书服务器我在本地试了一下也是奇慢无比，换域名后本地就正常了，估计是域名解析的问题

**Comment by dicarne** [comment]
你再试试，我重启了nginx，在我这访问比较正常了

**Comment by zycmayo** [comment]
> 你再尝试一下，我重新启动了nginx，在我这次访问中比较正常了

尝试了一下，已经解决了！非常感谢！
