### ISSUE TITLE
这两天频繁出现”下载错误，请检查权限申请情况！“

### ISSUE THREAD

**Issue by jackdiy** [dicarne/feishu-backup#29]
登录和授权，权限，检查一切正常。
刷新云文档目录很多次之后能请求文件夹了，但勾选下载文档不正常，只能下载几Mb就中断，说是下载成功。
上来请教各位有没有同样的问题。

**Comment by dicarne** [comment]
我发现某些请求飞书会返回404……怎么回事！用它给我的文档列表去访问文档会404！

**Comment by dicarne** [comment]
而且飞书会随机返回404，暂时不清楚什么毛病

**Comment by dicarne** [comment]
检测到链接某些飞书服务器的时候会挂，我重启了nginx，这边貌似不会报错了，奇怪

**Comment by dicarne** [comment]
原因是某些飞书服务器的ip发生了变更，但nginx仍然缓存了以前的ip，所以访问失败。
现在设置了缓存过期时间，以后理应不会经常发生这种问题。
这边测试没有问题，如果是自部署的话，参照  https://www.zhihu.com/question/61786355/answer/268735267 调整nginx后reload。
