### ISSUE TITLE
很喜欢你的文章！！

### ISSUE THREAD

**Issue by huangnuonan** [dicarne/feishu-backup#30]
hi～我是飞书开发者广场的运营同学，之前看到你这篇文章想法很不错，正好我们广场在做征稿活动，想问问能不能收录你的文章呀～

**Comment by dicarne** [comment]
好的～

**Comment by huangnuonan** [comment]
。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by huangnuonan** [comment]
哈哈太好了，这是我们的广场主页https://open.feishu.cn/community?sort=0&tag=7290376953627361281点击【我要投稿】就可以把文章发送到我们后台～ 然后这是我的飞书，方便咱们沟通下发稿事宜 Nuonan Huang申请添加你为联系人，点击链接处理 https://www.feishu.cn/invitation/page/add_contact/?token=833v99d7-1890-4a07-ade6-0d4cac66f3e9&amp;unique_id=22Ge8QnapQGUd3gdJi2tqA==

**Comment by huangnuonan** [comment]
。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
