### ISSUE TITLE
配置过程没有设置定向URL，导致网页无法打开，也无法进入配置页面

### ISSUE THREAD

**Issue by thzx805** [dicarne/feishu-backup#31]
配置过程没有设置定向URL，导致网页无法打开，也无法进入配置页面
提示请求非法, 请联系应用开发者，应如何重新设置

**Comment by thzx805** [comment]
有尝试过，但是提示404

**Comment by dicarne** [comment]
就是#号后面是config

**Comment by thzx805** [comment]
> 我发现我写错了，你试试http://127.0.0.1:18900/feishu-backup/#/config
这个链接可以打开了，非常感谢

**Comment by thzx805** [comment]
大佬，在下载过程中，经常报错，具体如下：

net/http: abort Handler
C:/Program Files/Go/src/net/http/httputil/reverseproxy.go:519 (0x840e68)
D:/Source/feishu-backup/main.go:56 (0x994bae)
C:/Users/hzdin/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x98b201)
C:/Users/hzdin/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102 (0x98b1ec)
C:/Users/hzdin/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x98a326)
C:/Users/hzdin/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240 (0x98a309)
C:/Users/hzdin/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174 (0x9893ca)
C:/Users/hzdin/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620 (0x989051)
C:/Users/hzdin/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576 (0x988cfc)
C:/Program Files/Go/src/net/http/server.go:2936 (0x81b035)
C:/Program Files/Go/src/net/http/server.go:1995 (0x817431)
C:/Program Files/Go/src/runtime/asm_amd64.s:1598 (0x616dc0)
[0m
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 200 with 500
[GIN] 2023/11/09 - 21:47:15 |[97;42m 200 [0m|    418.0273ms |       127.0.0.1 |[97;44m GET     [0m "/api/feishu/drive/v1/files/OxjvbYEBXohNY2xzHvRcgWXWnme/download"


大佬能帮忙看下可能是哪里的问题嘛？
文件都有管理权限

**Comment by dicarne** [comment]
看样子是反向代理飞书返回了500，感觉是网络问题，有下载成功的吗?还是全部失败？

**Comment by thzx805** [comment]
> 看样子是反向代理飞书返回了500，感觉是网络问题，有下载成功的吗?还是全部失败？

部分下载会成功，有时候报错很快，有时候要一会

**Comment by thzx805** [comment]
> > 看样子是反向代理飞书返回了500，感觉是网络问题，有下载成功的吗?还是全部失败？
> 
> 部分下载会成功，有时候报错很快，有时候要一会

下载后，图片都没了

**Comment by dicarne** [comment]
你这是云空间还是知识库？
我这边测试图片文档都能正常下载

**Comment by thzx805** [comment]
> 你这是云空间还是知识库？ 我这边测试图片文档都能正常下载

云文档的，下载MD，然后倒入就没图片了

**Comment by dicarne** [comment]
飞书服务器应该都不会全挂了，我写的只是个转发应该也没问题。
所以我觉得你是不是权限没有申请好？比如云空间云文件的相关权限？

**Comment by thzx805** [comment]
文件我都是可管理，检查过权限的，有时候下载会卡住半天不动，是因为网络不好嘛。

**Comment by dicarne** [comment]
你把程序关掉，试试这个 https://dicarne.github.io/feishu-backup/#/

**Comment by dicarne** [comment]
我看了代理的源码，是因为这个网络响应没有正常结束，那只能是因为网络问题了……

**Comment by thzx805** [comment]
> 我看了代理的源码，是因为这个网络响应没有正常结束，那只能是因为网络问题了……

是飞书的网络问题嘛。我用 https://dicarne.github.io/feishu-backup/#/也会卡在一个文件没响应

**Comment by dicarne** [comment]
好奇怪，我感觉你那里网络似乎不是很稳定，你要不翻墙试试（

**Comment by thzx805** [comment]
> 好奇怪，我感觉你那里网络似乎不是很稳定，你要不翻墙试试（

我试了2个不同省份的网络，也科学上网试过

**Comment by dicarne** [comment]
你大概下载了多少文件？会不会是太多了

**Comment by dicarne** [comment]
是随机文件不能下载，还是固定某几个不能下载？

**Comment by thzx805** [comment]
> 是随机文件不能下载，还是固定某几个不能下载？

用[https://dicarne.github.io/feishu-backup是固定一个文件，本地就不是

**Comment by dicarne** [comment]
那是个什么类型的文件，我看看能不能上传一个试试

**Comment by thzx805** [comment]
> 那是个什么类型的文件，我看看能不能上传一个试试

就是我在云空间上新建的一个文档

**Comment by dicarne** [comment]
用后面的在F12控制台有报错吗？还是只是单纯请求卡住了

**Comment by dicarne** [comment]
什么上传导入（愣住）

**Comment by thzx805** [comment]
> 什么上传导入（愣住）

我用大佬的工具下载了飞书上的文档，然后又用飞书导入了MD格式的文档，发现他没有带着文件夹里的图片上传，导致文件打开就没有图片了

**Comment by dicarne** [comment]
飞书还有这功能？！

**Comment by dicarne** [comment]
有意思

**Comment by dicarne** [comment]
可惜markdown是纯文本的

**Comment by youaremywind** [comment]
> 我发现我写错了，你试试http://127.0.0.1:18900/feishu-backup/#/config

使用这个也打不开

**Comment by dicarne** [comment]
> > 我发现我写错了，你试试http://127.0.0.1:18900/feishu-backup/#/config
> 
> 使用这个也打不开

我从最新的release中下载的程序，启动后，这个url可以打开没有问题。你启动程序了吗？命令窗口有什么错误信息吗

**Comment by youaremywind** [comment]
> > > 我发现我写错了，你试试http://127.0.0.1:18900/feishu-backup/#/config
> > 
> > 
> > 使用这个也打不开
> 
> 我从最新的release中下载的程序，启动后，这个url可以打开没有问题。你启动程序了吗？命令窗口有什么错误信息吗

<img width="1412" alt="image" src="https://github.com/dicarne/feishu-backup/assets/18423358/3b9cebd7-8f98-42b6-9572-7b344b465738">

**Comment by dicarne** [comment]
> > > > 我发现我写错了，你试试http://127.0.0.1:18900/feishu-backup/#/config
> > > 
> > > 
> > > 使用这个也打不开
> > 
> > 
> > 我从最新的release中下载的程序，启动后，这个url可以打开没有问题。你启动程序了吗？命令窗口有什么错误信息吗
> 
> <img alt="image" width="1412" src="https://private-user-images.githubusercontent.com/18423358/286168232-3b9cebd7-8f98-42b6-9572-7b344b465738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTcwNzksIm5iZiI6MTcwMTE1Njc3OSwicGF0aCI6Ii8xODQyMzM1OC8yODYxNjgyMzItM2I5Y2ViZDctOGY5OC00MmI2LTk1NzItN2IzNDRiNDY1NzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYTJiNzY4YTNlNWM5Mjk1MjUyOGU1MmUwMWNhZjExZmQzNjU0M2M1YjA4OGZiMGNmOWQ4YTYxNTNiZWYzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yl8GIIcfhrK0-PNN-NHpyRPBklWiHFCjnlfS7broOtA">

嘶mac，我没有mac，所以也没有调试的方法，只是打了个mac包，没想到默认会有问题。如果官方库没问题的话……你有没有移动过程序？这个程序要在dist文件夹的同级。

**Comment by youaremywind** [comment]
> > > > > 我发现我写错了，你试试http://127.0.0.1:18900/feishu-backup/#/config
> > > > 
> > > > 
> > > > 使用这个也打不开
> > > 
> > > 
> > > 我从最新的release中下载的程序，启动后，这个url可以打开没有问题。你启动程序了吗？命令窗口有什么错误信息吗
> > 
> > 
> > <img alt="image" width="1412" src="https://private-user-images.githubusercontent.com/18423358/286168232-3b9cebd7-8f98-42b6-9572-7b344b465738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTcwNzksIm5iZiI6MTcwMTE1Njc3OSwicGF0aCI6Ii8xODQyMzM1OC8yODYxNjgyMzItM2I5Y2ViZDctOGY5OC00MmI2LTk1NzItN2IzNDRiNDY1NzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYTJiNzY4YTNlNWM5Mjk1MjUyOGU1MmUwMWNhZjExZmQzNjU0M2M1YjA4OGZiMGNmOWQ4YTYxNTNiZWYzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yl8GIIcfhrK0-PNN-NHpyRPBklWiHFCjnlfS7broOtA">
> 
> 嘶mac，我没有mac，所以也没有调试的方法，只是打了个mac包，没想到默认会有问题。如果官方库没问题的话……你有没有移动过程序？这个程序要在dist文件夹的同级。

linux 呢  我都没动过 都进不去

**Comment by dicarne** [comment]
> > > > > > 我发现我写错了，你试试http://127.0.0.1:18900/feishu-backup/#/config
> > > > > 
> > > > > 
> > > > > 使用这个也打不开
> > > > 
> > > > 
> > > > 我从最新的release中下载的程序，启动后，这个url可以打开没有问题。你启动程序了吗？命令窗口有什么错误信息吗
> > > 
> > > 
> > > <img alt="image" width="1412" src="https://private-user-images.githubusercontent.com/18423358/286168232-3b9cebd7-8f98-42b6-9572-7b344b465738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTcwNzksIm5iZiI6MTcwMTE1Njc3OSwicGF0aCI6Ii8xODQyMzM1OC8yODYxNjgyMzItM2I5Y2ViZDctOGY5OC00MmI2LTk1NzItN2IzNDRiNDY1NzM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MzI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYTJiNzY4YTNlNWM5Mjk1MjUyOGU1MmUwMWNhZjExZmQzNjU0M2M1YjA4OGZiMGNmOWQ4YTYxNTNiZWYzYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yl8GIIcfhrK0-PNN-NHpyRPBklWiHFCjnlfS7broOtA">
> > 
> > 
> > 嘶mac，我没有mac，所以也没有调试的方法，只是打了个mac包，没想到默认会有问题。如果官方库没问题的话……你有没有移动过程序？这个程序要在dist文件夹的同级。
> 
> linux 呢 我都没动过 都进不去

那你怎么下了mac程序，linux的程序没有`-mac`后缀
![image](https://github.com/dicarne/feishu-backup/assets/10357789/f99d21dc-c385-430c-8530-1037ef264dce)

**Comment by dicarne** [comment]
我这边测试linux版是正常的，mac我没有所以只能祈祷正常（

**Comment by youaremywind** [comment]
> 我这边测试linux版是正常的，mac我没有所以只能祈祷正常（

不好意思  我没描述清楚 mac 和 Linux 服务器我都尝试了都没有成功😭

**Comment by dicarne** [comment]
> > 我这边测试linux版是正常的，mac我没有所以只能祈祷正常（
> 
> 不好意思 我没描述清楚 mac 和 Linux 服务器我都尝试了都没有成功😭

神奇，会不会是因为某种原因文件夹权限不对，比如文件夹不可读什么的（只能想到这个原因了）

**Comment by dicarne** [comment]
还有我看说要在那个目录下启动程序，比如`./xxxx`的，不能在其他目录启动

**Comment by youaremywind** [comment]
> > > 我这边测试linux版是正常的，mac我没有所以只能祈祷正常（
> > 
> > 
> > 不好意思 我没描述清楚 mac 和 Linux 服务器我都尝试了都没有成功😭
> 
> 神奇，会不会是因为某种原因文件夹权限不对，比如文件夹不可读什么的（只能想到这个原因了）

权限是都有的 telnet 是不通的 我是./feishu-backup 启动的
<img width="932" alt="image" src="https://github.com/dicarne/feishu-backup/assets/18423358/4bf95518-6355-4c03-9569-9aa87851d1f1">

**Comment by dicarne** [comment]
这是在其他服务器上装的？

**Comment by dicarne** [comment]
> > 这是在其他服务器上装的？
> 
> 是的 我现在放虚拟机和我的腾讯云的 Linux 服务器都是不行 ，运行是没有报错的

那确实有问题，这是给本机用的，所以网页写了localhost……

**Comment by dicarne** [comment]
> > 这是在其他服务器上装的？
> 
> 是的 我现在放虚拟机和我的腾讯云的 Linux 服务器都是不行 ，运行是没有报错的

你要在服务器上用的话不需要这个程序，只需要把dist文件夹当成静态网站配置就可以了

**Comment by youaremywind** [comment]
> > > 这是在其他服务器上装的？
> > 
> > 
> > 是的 我现在放虚拟机和我的腾讯云的 Linux 服务器都是不行 ，运行是没有报错的
> 
> 那确实有问题，这是给本机用的，所以网页写了localhost……

用Windows 成功下了
