### ISSUE TITLE
可以支持一下文字高亮的导出吗？

### ISSUE THREAD

**Issue by guigui0114** [dicarne/feishu-backup#33]
因为我想保持笔记的扁平结构，所以有些Head是用文字高亮来表达的，但是下下来以后没有高亮了/(ㄒoㄒ)/~~

**Comment by dicarne** [comment]
高亮不是标准markdown语法，但是可以用标签实现
例如：
`你好，<mark style="background-color: #66ccff" >嘿嘿</mark>`
我写一下

**Comment by dicarne** [comment]
https://github.com/dicarne/feishu-backup/releases/tag/v0.2.3

尝试一下这个版本

**Comment by guigui0114** [comment]
没有！我试了一下下载下来的文档里还是没有高亮/(ㄒoㄒ)/~~

<span style="background-color: #F2F3F5">背景高亮为浅灰色的文字。</span>
<span style="background-color: #FBBFBC">背景高亮为浅红色的文字。</span>
<span style="background-color: #FEDDB6">背景高亮为浅橙色的文字。</span>
<span style="background-color: #FEF794">背景高亮为浅黄色的文字。</span>
<span style="background-color: #C3EEC0">背景高亮为浅绿色的文字。</span>
<span style="background-color: #CDDAFB">背景高亮为浅蓝色的文字。</span>
<span style="background-color: #DCC9FB">背景高亮为浅紫色的文字。</span>
<span style="background-color: #E5E6E9">背景高亮为中灰色的文字。</span>
<span style="background-color: #BBBFC4">背景高亮为深灰色的文字。</span>
<span style="background-color: #F76964">背景高亮为红色的文字。</span>
<span style="background-color: #FFA53D">背景高亮为橙色的文字。</span>
<span style="background-color: #FFE928">背景高亮为黄色的文字。</span>
<span style="background-color: #62D256">背景高亮为绿色的文字。</span>
<span style="background-color: #9EBBFE">背景高亮为蓝色的文字。</span>
<span style="background-color: #C4A4FA">背景高亮为紫色的文字。</span>

这是我吸出来的颜色代码，能不能麻烦你搞一哈
![image](https://github.com/dicarne/feishu-backup/assets/125194895/b8f3e08e-5365-4e96-8e62-1f5c4ccbeda3)

**Comment by dicarne** [comment]
嗯？我再看看

**Comment by guigui0114** [comment]
```
<span style="background-color: #F2F3F5">背景高亮为浅灰色的文字。</span>
<span style="background-color: #FBBFBC">背景高亮为浅红色的文字。</span>
<span style="background-color: #FEDDB6">背景高亮为浅橙色的文字。</span>
<span style="background-color: #FEF794">背景高亮为浅黄色的文字。</span>
<span style="background-color: #C3EEC0">背景高亮为浅绿色的文字。</span>
<span style="background-color: #CDDAFB">背景高亮为浅蓝色的文字。</span>
<span style="background-color: #DCC9FB">背景高亮为浅紫色的文字。</span>
<span style="background-color: #E5E6E9">背景高亮为中灰色的文字。</span>
<span style="background-color: #BBBFC4">背景高亮为深灰色的文字。</span>
<span style="background-color: #F76964">背景高亮为红色的文字。</span>
<span style="background-color: #FFA53D">背景高亮为橙色的文字。</span>
<span style="background-color: #FFE928">背景高亮为黄色的文字。</span>
<span style="background-color: #62D256">背景高亮为绿色的文字。</span>
<span style="background-color: #9EBBFE">背景高亮为蓝色的文字。</span>
<span style="background-color: #C4A4FA">背景高亮为紫色的文字。</span>
```

**Comment by guigui0114** [comment]
```
<span style="color: #D5D7DA;">这是灰色的字体。</span>
<span style="color: #DB4F48;">这是红色的字体。</span>
<span style="color: #E28922;">这是橙色的字体。</span>
<span style="color: #DDA011;">这是黄色的字体。</span>
<span style="color: #3DA731;">这是绿色的字体。</span>
<span style="color: #4372DE;">这是蓝色的字体。</span>
<span style="color: #6B31CB;">这是紫色的字体。</span>
```

**Comment by dicarne** [comment]
我这可以正常显示高亮，你用的是什么markdown软件？

**Comment by dicarne** [comment]
https://github.com/dicarne/feishu-backup/releases/tag/v0.2.4

你再试试这个，记住打开后再网页按以下ctrl+F5，不然有可能浏览器缓存的是之前的文件，访问不到新的版本。

**Comment by guigui0114** [comment]
typora, 那我用obsidian打开试试，我一般写笔记都用typora，你用的是啥软件哇？
因为我不会写代码，之前问过ChatGPT咋实现高亮，
然后他告诉我用<mark>标签或者<span>标签，
但我在typora里试了，<mark>标签有时候不太好使？？
这是我之前记得笔记
![image](https://github.com/dicarne/feishu-backup/assets/125194895/669b2588-13a8-4b6b-811d-78d1c1011d6f)
但我现在有点记不清楚具体是不是标签的问题了，我刚刚试了一下在typora里面<mark>也能使，

但反正<span>在typora和 obsidian 里面都能用

**Comment by dicarne** [comment]
哈哈，我debug的时候用vscode的markdown，笔记的话obsidian

**Comment by dicarne** [comment]
可能typora后来更新支持了……
现在应该没问题了八？

**Comment by dicarne** [comment]
还是觉得高亮用mark标签更好，用span的话里面文字颜色很容易看不清（深色背景的话）

**Comment by guigui0114** [comment]
好了！！！！！！你人怪好叻！！！
但是这有一段有斜体的出问题了
![image](https://github.com/dicarne/feishu-backup/assets/125194895/699250db-c186-4069-a585-3d25f45ac9ff)
这个能解决吗？不过问题不大！因为不咋用斜体，开心！！！

**Comment by guigui0114** [comment]
> 还是觉得高亮用mark标签更好，用span的话里面文字颜色很容易看不清（深色背景的话）

我不懂这个耶，学到了，嘿嘿

**Comment by dicarne** [comment]
能把出问题那段的markdown贴给我看看吗？

**Comment by guigui0114** [comment]
> 能把出问题那段的markdown贴给我看看吗？

https://qt932dqqz5.feishu.cn/docx/EnnQdMRCeofB8uxkr4scugPmnRd

**Comment by guigui0114** [comment]
> 能把出问题那段的markdown贴给我看看吗？

```
This kind of reminds me of**<span style="background-color: #C0ECBC">*Color and Light*</span>by <span style="background-color: #C0ECBC">*James Gurney*</span>, and there's one particular exercise on page 138. We have these color swatches here, and then James Gurney has them during the day, and a simulated version of them <span style="background-color: #C0ECBC">at night time</span>. So notice a lot of <span style="background-color: #C0ECBC">these colors lose their perceived saturation and hue</span>. And in Hilda, this is pushed even further by losing them entirely.
```

**Comment by guigui0114** [comment]
是不是斜体的那个*语法跟<span>冲突了？

我刚刚发现一件事，就是说..下划线不见了，要不你把下划线也加进去呗，嘿嘿
![096E158D](https://github.com/dicarne/feishu-backup/assets/125194895/40f331c9-acd2-4bb2-917c-43c6102110a9)

**Comment by dicarne** [comment]
我发现是一个斜体的空格导致的，哈哈哈，修一下

**Comment by dicarne** [comment]
https://github.com/dicarne/feishu-backup/releases/tag/v0.2.5

你瞅瞅，我这看起来挺正常的，下划线也加了

**Comment by guigui0114** [comment]
> https://github.com/dicarne/feishu-backup/releases/tag/v0.2.5
> 
> 
> 
> 你瞅瞅，我这看起来挺正常的，下划线也加了

**Comment by guigui0114** [comment]
> https://github.com/dicarne/feishu-backup/releases/tag/v0.2.5
> 
> 你瞅瞅，我这看起来挺正常的，下划线也加了

太棒啦！感谢！！！为宁送上一只锦旗~嘿嘿
![GitHub-feishu-backup-锦旗](https://github.com/dicarne/feishu-backup/assets/125194895/8a597804-5230-4d79-87e4-5be2fa7d6e82)

**Comment by dicarne** [comment]
哈哈哈哈你真好玩，画的真好！有什么需求再来～
