### ISSUE TITLE
无序列表只有第一层

### ISSUE THREAD

**Issue by guigui0114** [dicarne/feishu-backup#34]
我发现在飞书文档里写了无序列表，下载后只有第一层级还在，其他层级都没有保留。像下图这样：
![PixPin_2024-01-31_00-58-35](https://github.com/dicarne/feishu-backup/assets/125194895/3781197a-2c9a-403d-9da2-90b1df18933a)
有时候我为了让上下文文本对齐，可能会写到第三层。
所以有没有一种可能就是说，老大你可以给无序列表多加几个层级吗？
![08032533](https://github.com/dicarne/feishu-backup/assets/125194895/8ba2f45d-a587-448f-87e1-9fd0f0ff68be)

有序列表我没有试，但我觉得可能也有这个问题。如果有序列表也能加一层就太棒啦！
还有一个小小的问题是，有序列表下下来以后没有排序了？每一条都是第一条，像下面这样：
![image](https://github.com/dicarne/feishu-backup/assets/125194895/d709aca6-7273-4220-b7a3-9b981cc52e6d)

嗯嗯就是这些问题，老板看看能不能搞一搞
![080C240E](https://github.com/dicarne/feishu-backup/assets/125194895/7eefc575-c4a5-4b02-b1f0-f032c2bcd846)

**Comment by guigui0114** [comment]
我刚刚又发现一个问题，`## 标题2`以及`标题2下面的内容`全部都丢失了，只有`# 标题1`下面的内容还在？？是我的问题吗？我用的V0.2.5

**Comment by guigui0114** [comment]
还有一个关于缩进的问题，在飞书里按Tab缩进的地方，在Ob里面没有缩进。
（哎呀我好像提了太多需求，怪不好意思的

**Comment by dicarne** [comment]
咦居然列表有问题吗，我看看

**Comment by dicarne** [comment]
关于有序列表偷懒的问题——主要是我的编辑器他会自己把相同的`1.`、`1.`渲染成`1.`、`2.`哈哈，没想到有编辑器不支持这个功能

**Comment by dicarne** [comment]
> 还有一个关于缩进的问题，在飞书里按Tab缩进的地方，在Ob里面没有缩进。 （哎呀我好像提了太多需求，怪不好意思的

这个可能解决不了。
一方面是给我的数据里就没有缩进。
另一方面tab缩进不是Markdown支持的方法，Markdown渲染时实际上是会忽视这些字符，我在OD中尝试手动用tab缩进，切换到阅读视图时缩进也不存在了。另外，空格缩进也是没有用的。
应该考虑用其他的方式排版。

**Comment by dicarne** [comment]
https://github.com/dicarne/feishu-backup/releases/tag/0.2.7

**Comment by dicarne** [comment]
https://github.com/dicarne/feishu-backup/releases/tag/0.2.7

可以尝试一下。打开网页后可以先ctrl+f5强制刷新一下，避免获取到旧版本。

**Comment by guigui0114** [comment]
> 关于有序列表偷懒的问题——主要是我的编辑器他会自己把相同的`1.`、`1.`渲染成`1.`、`2.`哈哈，没想到有编辑器不支持这个功能

你用的编辑器不是obsidian吗？我就是用obsidian打开的。你是不是换编辑器啦？换成啥啦？

**Comment by dicarne** [comment]
> > 关于有序列表偷懒的问题——主要是我的编辑器他会自己把相同的`1.`、`1.`渲染成`1.`、`2.`哈哈，没想到有编辑器不支持这个功能
> 
> 你用的编辑器不是obsidian吗？我就是用obsidian打开的。你是不是换编辑器啦？换成啥啦？

不是不是，没换，是写代码的编辑器XD

**Comment by guigui0114** [comment]
> > 还有一个关于缩进的问题，在飞书里按Tab缩进的地方，在Ob里面没有缩进。 （哎呀我好像提了太多需求，怪不好意思的
> 
> 这个可能解决不了。 一方面是给我的数据里就没有缩进。 另一方面tab缩进不是Markdown支持的方法，Markdown渲染时实际上是会忽视这些字符，我在OD中尝试手动用tab缩进，切换到阅读视图时缩进也不存在了。另外，空格缩进也是没有用的。 应该考虑用其他的方式排版。

原来是这样，我这几天在尝试把笔记都挪到ob里面，但是感觉在ob里面编辑特别难受，没有typora丝滑。双链和块的引用也没用出个所以然。
你有写过什么关于知识管理的文章吗？我觉得你可能有些独到的见解，你是少数派作者吗？我可以去关注一波吗？
你写的这个飞书的插件（是叫插件吧？）初衷是什么哇？在你的工作流里是个什么功能？
我用飞书主要是为了用妙记，后来发现这个飞书文档还怪好用的。我昨天晚上一度迷惑我为什么要把这些笔记挪来挪去，还没有用Word来的效率高。。。我现在脑袋里一团浆糊，我先来试一下这个V0.2.6

**Comment by guigui0114** [comment]
貌似还有点问题，
无序列表和有序列表的层级没有问题了，像下面这样：
![PixPin_2024-01-31_17-39-54](https://github.com/dicarne/feishu-backup/assets/125194895/56def14f-0f7d-406b-af91-6ef8dc5f6ce9)
![PixPin_2024-01-31_17-42-51](https://github.com/dicarne/feishu-backup/assets/125194895/8e75295a-0cf3-4a4d-bffd-62765cc81e04)

但是下面这两种情况是咋回事？

1. 所有三级标题和里面的内容都没了？
![PixPin_2024-01-31_17-46-55](https://github.com/dicarne/feishu-backup/assets/125194895/aeef04da-5d2e-476a-b9dc-3a5e638402af)

2. 二级标题后面直接跟无序列表，然后列表没了？我不知道我当时为啥手欠把这个列表缩进了，但反正这个缩进了的无序列表丢了。
![PixPin_2024-01-31_17-51-21](https://github.com/dicarne/feishu-backup/assets/125194895/68ec557b-4ed0-46e9-8425-6ba9bc0de57a)

**Comment by dicarne** [comment]
估计是缩进的原因，刚才尝试了一下没有复现，可能是变成了子级吧

**Comment by dicarne** [comment]
> > > 还有一个关于缩进的问题，在飞书里按Tab缩进的地方，在Ob里面没有缩进。 （哎呀我好像提了太多需求，怪不好意思的
> > 
> > 
> > 这个可能解决不了。 一方面是给我的数据里就没有缩进。 另一方面tab缩进不是Markdown支持的方法，Markdown渲染时实际上是会忽视这些字符，我在OD中尝试手动用tab缩进，切换到阅读视图时缩进也不存在了。另外，空格缩进也是没有用的。 应该考虑用其他的方式排版。
> 
> 原来是这样，我这几天在尝试把笔记都挪到ob里面，但是感觉在ob里面编辑特别难受，没有typora丝滑。双链和块的引用也没用出个所以然。 你有写过什么关于知识管理的文章吗？我觉得你可能有些独到的见解，你是少数派作者吗？我可以去关注一波吗？ 你写的这个飞书的插件（是叫插件吧？）初衷是什么哇？在你的工作流里是个什么功能？ 我用飞书主要是为了用妙记，后来发现这个飞书文档还怪好用的。我昨天晚上一度迷惑我为什么要把这些笔记挪来挪去，还没有用Word来的效率高。。。我现在脑袋里一团浆糊，我先来试一下这个V0.2.6

这个的主要功能是备份迁移嘛，哪天不想用飞书文档了就可以下载下来。（前车之鉴：有道云笔记的倒闭，语雀的崩溃）
一般选个自己喜欢的笔记就好了呀，我不太清楚你的流程是怎么样的，一般应该不存在整天移来移去的情况。

**Comment by dicarne** [comment]
> 貌似还有点问题， 无序列表和有序列表的层级没有问题了，像下面这样： ![PixPin_2024-01-31_17-39-54](https://private-user-images.githubusercontent.com/125194895/301117553-56def14f-0f7d-406b-af91-6ef8dc5f6ce9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYwMzMsIm5iZiI6MTcwNjY5NTczMywicGF0aCI6Ii8xMjUxOTQ4OTUvMzAxMTE3NTUzLTU2ZGVmMTRmLTBmN2QtNDA2Yi1hZjkxLTZlZjhkYzVmNmNlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxMDA4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjdmZmIwNGMxOGU1Y2YzODQ2OWE3YjMzMGNlNTEzOWYwYzdhMGRlYzFiNmNjMWJiMjljOTMzMjIyM2E0ZjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wcXhfEKLPfHQlan6EHAlcIQTelmxyMFbtdouvWatf1I) ![PixPin_2024-01-31_17-42-51](https://private-user-images.githubusercontent.com/125194895/301117619-8e75295a-0cf3-4a4d-bffd-62765cc81e04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYwMzMsIm5iZiI6MTcwNjY5NTczMywicGF0aCI6Ii8xMjUxOTQ4OTUvMzAxMTE3NjE5LThlNzUyOTVhLTBjZjMtNGE0ZC1iZmZkLTYyNzY1Y2M4MWUwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxMDA4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODVlMTBhNDZhNjZkYzIyNmU3OTg5NjViZWViM2Q5NWY3MDllM2Y0ZmE5ODdmZGZlODk4ODUwNzBjNGRkMzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ao62u4tQGwpNgT6ENDr3xCpmm_qYb6R7WY0xlsAWMck)
> 
> 但是下面这两种情况是咋回事？
> 
> 1. 所有三级标题和里面的内容都没了？
>    ![PixPin_2024-01-31_17-46-55](https://private-user-images.githubusercontent.com/125194895/301118238-aeef04da-5d2e-476a-b9dc-3a5e638402af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYwMzMsIm5iZiI6MTcwNjY5NTczMywicGF0aCI6Ii8xMjUxOTQ4OTUvMzAxMTE4MjM4LWFlZWYwNGRhLTVkMmUtNDc2YS1iOWRjLTNhNWU2Mzg0MDJhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxMDA4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2NjMmI1MGZmYzFmZmE0ZWQxOGVhN2YzMWIyNGQwNmRhNjgyNmQ1YWIzZmNjMTJhMzYzNTk5NWExYzAzNmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YOlC6C5SfEvwwUYOQNMY99FmSiG_L9SMZ-_-c3Fj99Q)
> 2. 二级标题后面直接跟无序列表，然后列表没了？我不知道我当时为啥手欠把这个列表缩进了，但反正这个缩进了的无序列表丢了。
>    ![PixPin_2024-01-31_17-51-21](https://private-user-images.githubusercontent.com/125194895/301120180-68ec557b-4ed0-46e9-8425-6ba9bc0de57a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTYwMzMsIm5iZiI6MTcwNjY5NTczMywicGF0aCI6Ii8xMjUxOTQ4OTUvMzAxMTIwMTgwLTY4ZWM1NTdiLTRlZDAtNDZlOS04NDI1LTZiYTliYzBkZTU3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxMDA4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MGIzNWNkNWRlYTliYTc1NjMxNGZiYzU3MTBhMTY5YTkwYTVlZGFjZTc2N2NhMjI2ZjJhMzAyMzJmN2RjYjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.A6nsQjdFTZvvLE14xBGvtdFdtap_pEbgtTPy99qt8_I)

如果可以把这个有问题的文档发给我的话，不胜感激！
飞书这个子级的功能非常奇葩，令人头疼并且看不出什么意义。

**Comment by dicarne** [comment]
> > 估计是缩进的原因，刚才尝试了一下没有复现，可能是变成了子级吧
> 
> 我知道了，就是不要缩进对吧，换行以后叭叭打字就不会出问题。

主要是刚才我把它搞成子级也没出问题，反正很奇怪，不知道他怎么算的

**Comment by guigui0114** [comment]
咋发给你，GitHub可以发私信吗？我没找着

**Comment by dicarne** [comment]
> 咋发给你，GitHub可以发私信吗？我没找着

好像没这个功能，不发也可以，我大概知道怎么解决

**Comment by guigui0114** [comment]
https://qt932dqqz5.feishu.cn/docx/SebPdhDMmoxb7hxKxhxcFwXenmd?from=from_copylink

我直接粘在这吧，一会给它删了嘿嘿

**Comment by dicarne** [comment]
> https://qt932dqqz5.feishu.cn/docx/SebPdhDMmoxb7hxKxhxcFwXenmd?from=from_copylink
> 
> 我直接粘在这吧，一会给它删了嘿嘿

可以，可以删了

**Comment by guigui0114** [comment]
你引用嘎哈？你也删了

**Comment by dicarne** [comment]
> 你引用嘎哈？你也删了

啥，我拷贝一个副本，然后你就可以直接把连接删了呀

**Comment by dicarne** [comment]
https://github.com/dicarne/feishu-backup/releases/tag/v0.2.7
我改了改，目前没看出什么问题

**Comment by dicarne** [comment]
笑死，我的我的

**Comment by guigui0114** [comment]
> 笑死，我的我的

没有问题了！太棒了！开心
![0104EC34](https://github.com/dicarne/feishu-backup/assets/125194895/44e37bf7-b766-435c-8d34-29bc6f1bf5b9)
