### ISSUE TITLE
是不是企业版需要领导才能审批权限啊？

### ISSUE THREAD

**Issue by abevol** [dicarne/feishu-backup#4]
建议在README里说明一下

**Comment by dicarne** [comment]
是的，所有权限都需要管理员审批

**Comment by dicarne** [comment]
所以我说是为个人用户设计，一般企业领导是不会让员工把文档搬走的……这可是公司的财产！（虽然是你自己写的）

**Comment by abevol** [comment]
> 

谢谢，我找到了个笨办法，直接全选复制，然后在个人版的账号里新建文档，粘贴进去就可以了。
