### ISSUE TITLE
点击下载云空间文档按钮显示下载失败

### ISSUE THREAD

**Issue by rovertang** [dicarne/feishu-backup#5]
![image](https://user-images.githubusercontent.com/1571397/177041690-2b65d3f2-caad-4715-b764-ae9f624d491c.png)
如图所示，已经授权成功了，然后点了下载云空间文档按钮，结果就显示下载失败的提示了，下拉列表也显示为nodata。
说明，是自建服务，放在了服务器上，Nginx的配置应该是OK的。这提示是我哪里配置错了吗？

**Comment by dicarne** [comment]
你看下f12的里的网络请求，看看有没有报错或者失败的请求返回了什么。
一般来说，可能是没有正确赋予足够的权限……

**Comment by rovertang** [comment]
> 你看下f12的里的网络请求，看看有没有报错或者失败的请求返回了什么。 一般来说，可能是没有正确赋予足够的权限……

调试了一下，两个地方错误：
1、URL错了
在/secret.ts内容：http://your.domain/YOUR_URL
这个地方填错了，同后面 配置转发的Nginx例子：location /your_url  这个不一致，导致需要转发的URL实际上没有做proxy。

2、docx文件没有申请权限
因为docx是最近出的，API原来没有这个权限，所以默认是没有申请的。
对于没有权限的情况，会提示：
    "code": 99991672,
    "msg": "No permission. One of the following scopes is required: [docx:document, docx:document:readonly]",
参考：                "url": "https://open.feishu.cn/document/ukTMukTMukTM/uYTM5UjL2ETO14iNxkTN/scope-list",

希望这些能给遇到相同问题的同学做参考。
另外遇到的bug问题再单独开一贴。
