### ISSUE TITLE
下载的md文件，图片未带.png后缀

### ISSUE THREAD

**Issue by rovertang** [dicarne/feishu-backup#7]
如题
下载了md文件，里面的图片链接，不带.png
比如：
![](assets/boxcnxwVAApOZv6emUnEoAihhle)
实际文件是：boxcnxwVAApOZv6emUnEoAihhle.png
所以图片的这个路径，应该要带.png后缀的哦，不然无法显示出来呢。
还烦请修复一下。谢谢
如有其他需求，另提。感谢。

**Comment by dicarne** [comment]
居然直接被关了……这是一个因为并发下载引入的bug，没有想到比较简单的好办法，就先改回串行，起码不会有问题。

**Comment by rovertang** [comment]
测试可用。文件后缀给带上了。不过发现上次下载成功是jpg文件，现在是jpeg文件了。

**Comment by dicarne** [comment]
这个是根据mime type决定的，应该不会有显示问题吧。

**Comment by rovertang** [comment]
> 这个是根据mime type决定的，应该不会有显示问题吧。

没有，jpeg也一样能够显示，浏览器没看出什么问题来。
我主要是飞书下载下来后送进hugo的，简单方便，省去自己编辑图片的麻烦。

**Comment by dicarne** [comment]
之前硬编码了将jpeg改成jpg，后来想想并没有必要，就去掉了，所以会不一样
