### ISSUE TITLE
一开始可以下载，文件很多，大概2~3小时后就失败了

### ISSUE THREAD

**Issue by hihihowareyou** [dicarne/feishu-backup#8]
后面再也不能下载了，云空间文档显示下载错误，选择文件显示No data。
下载知识库文档则空白没有文件。
一开始是成功的，云空间可以完整下载，知识库也在进行中。是不是文档太多了，导致飞书后台做了封锁？

**Comment by dicarne** [comment]
你这可能……太多了，我没有试过这么海量的文件

**Comment by hihihowareyou** [comment]
明白了。感谢

**Comment by dicarne** [comment]
增加了续期的机制，目前测试是没问题，不过具体要看看过期后是不是真的不会有问题，那只能明天试试了

**Comment by hihihowareyou** [comment]
我测下来还是不行，原因未知。我看了下我有1000多个文档。。

**Comment by lmmsoft** [comment]
+1,最近要备份大量文档（飞书收费），感觉是内存爆了？

**Comment by dicarne** [comment]
> +1,最近要备份大量文档（飞书收费），感觉是内存爆了？

有可能？但我没有这么多文档进行测试
