### ISSUE TITLE
无法下载，出现99991401错误，则请去后台添加IP白名单

### ISSUE THREAD

**Issue by rovertang** [dicarne/feishu-backup#9]
如题
因为切换了个服务器，所以遇到了99991401错误
网址都能访问了，竟然无法下载下来文件？
具体看图
![image](https://user-images.githubusercontent.com/1571397/180628580-af991b43-e967-4e46-a662-64239e8c6270.png)

去后台添加IP白名单就可以用啦。
我只是正好遇到，截图都截好了，那就过来发一下吧，希望能帮上遇到相同问题的同学。

**Comment by dicarne** [comment]
感谢！
